"""Initial migration with all tables

Revision ID: 344c745e1f4b
Revises:
Create Date: 2026-02-04 05:04:31.599470

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "344c745e1f4b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "email", sa.String(length=255), nullable=False, comment="Email пользователя"
        ),
        sa.Column(
            "username", sa.String(length=100), nullable=True, comment="Имя пользователя"
        ),
        sa.Column(
            "full_name",
            sa.String(length=255),
            nullable=True,
            comment="Полное имя пользователя",
        ),
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=True,
            comment="Хешированный пароль",
        ),
        sa.Column(
            "avatar_url", sa.String(length=500), nullable=True, comment="URL аватара"
        ),
        sa.Column(
            "github_id",
            sa.String(length=100),
            nullable=True,
            comment="GitHub ID пользователя",
        ),
        sa.Column(
            "github_username",
            sa.String(length=100),
            nullable=True,
            comment="GitHub имя пользователя",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активен ли пользователь"
        ),
        sa.Column(
            "is_verified", sa.Boolean(), nullable=False, comment="Подтвержден ли email"
        ),
        sa.Column(
            "role",
            postgresql.ENUM("ADMIN", "USER", name="userrole"),
            nullable=False,
            comment="Роль пользователя",
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Последний вход в систему",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "projects",
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Название проекта"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание проекта"),
        sa.Column(
            "status",
            postgresql.ENUM(
                "ACTIVE", "COMPLETED", "ARCHIVED", "ON_HOLD", name="projectstatus"
            ),
            nullable=False,
            comment="Статус проекта",
        ),
        sa.Column(
            "is_public", sa.Boolean(), nullable=False, comment="Публичный ли проект"
        ),
        sa.Column(
            "owner_id", sa.UUID(), nullable=False, comment="ID владельца проекта"
        ),
        sa.Column(
            "allow_external_sharing",
            sa.Boolean(),
            nullable=False,
            comment="Разрешить внешний доступ",
        ),
        sa.Column(
            "max_members",
            sa.String(length=10),
            nullable=False,
            comment="Максимальное количество участников",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_id"), "projects", ["id"], unique=False)
    op.create_table(
        "project_members",
        sa.Column("project_id", sa.UUID(), nullable=False, comment="ID проекта"),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="ID пользователя"),
        sa.Column(
            "role",
            postgresql.ENUM("OWNER", "MEMBER", "VIEWER", name="projectrole"),
            nullable=False,
            comment="Роль в проекте",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активен ли участник"
        ),
        sa.Column(
            "invited_by_id", sa.UUID(), nullable=True, comment="Кто пригласил участника"
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_members_id"), "project_members", ["id"], unique=False
    )
    op.create_table(
        "sprints",
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Название спринта"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание спринта"),
        sa.Column("goal", sa.Text(), nullable=True, comment="Цель спринта"),
        sa.Column(
            "status",
            postgresql.ENUM(
                "planning", "active", "completed", "cancelled", name="sprintstatus"
            ),
            nullable=False,
            comment="Статус спринта",
        ),
        sa.Column(
            "start_date", sa.Date(), nullable=True, comment="Дата начала спринта"
        ),
        sa.Column(
            "end_date", sa.Date(), nullable=True, comment="Дата окончания спринта"
        ),
        sa.Column("project_id", sa.UUID(), nullable=False, comment="ID проекта"),
        sa.Column(
            "capacity_hours",
            sa.Integer(),
            nullable=True,
            comment="Емкость спринта в часах",
        ),
        sa.Column(
            "velocity_points",
            sa.Integer(),
            nullable=True,
            comment="Планируемая скорость в Story Points",
        ),
        sa.Column(
            "completed_points",
            sa.Integer(),
            nullable=False,
            comment="Выполненные Story Points",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sprints_id"), "sprints", ["id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column(
            "title", sa.String(length=255), nullable=False, comment="Название задачи"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание задачи"),
        sa.Column(
            "status",
            postgresql.ENUM(
                "todo", "in_progress", "in_review", "done", "blocked", name="taskstatus"
            ),
            nullable=False,
            comment="Статус задачи",
        ),
        sa.Column(
            "priority",
            postgresql.ENUM("low", "medium", "high", "urgent", name="taskpriority"),
            nullable=False,
            comment="Приоритет задачи",
        ),
        sa.Column(
            "story_point",
            postgresql.ENUM(
                "1", "2", "3", "5", "8", "13", "21", "unknown", name="storypoint"
            ),
            nullable=False,
            comment="Оценка в Story Points",
        ),
        sa.Column(
            "order", sa.Integer(), nullable=False, comment="Порядок в колонке Kanban"
        ),
        sa.Column("project_id", sa.UUID(), nullable=False, comment="ID проекта"),
        sa.Column(
            "creator_id", sa.UUID(), nullable=False, comment="ID создателя задачи"
        ),
        sa.Column(
            "assignee_id", sa.UUID(), nullable=True, comment="ID исполнителя задачи"
        ),
        sa.Column(
            "parent_task_id", sa.UUID(), nullable=True, comment="ID родительской задачи"
        ),
        sa.Column(
            "due_date", sa.String(length=20), nullable=True, comment="Срок выполнения"
        ),
        sa.Column(
            "estimated_hours",
            sa.Integer(),
            nullable=True,
            comment="Оценка времени в часах",
        ),
        sa.Column(
            "actual_hours",
            sa.Integer(),
            nullable=False,
            comment="Фактическое время в часах",
        ),
        sa.Column(
            "is_archived",
            sa.Boolean(),
            nullable=False,
            comment="Архивирована ли задача",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_table(
        "comments",
        sa.Column(
            "content", sa.Text(), nullable=False, comment="Содержание комментария"
        ),
        sa.Column("task_id", sa.UUID(), nullable=False, comment="ID задачи"),
        sa.Column("author_id", sa.UUID(), nullable=False, comment="ID автора"),
        sa.Column(
            "is_edited",
            sa.Boolean(),
            nullable=False,
            comment="Отредактирован ли комментарий",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_comments_id"), "comments", ["id"], unique=False)
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("notification_type", sa.String(length=50), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("task_id", sa.Uuid(), nullable=True),
        sa.Column("sprint_id", sa.Uuid(), nullable=True),
        sa.Column("action_url", sa.String(length=500), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sprint_id"], ["sprints.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"),
        "notifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_index(
        op.f("ix_notifications_is_read"), "notifications", ["is_read"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_notification_type"),
        "notifications",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_project_id"),
        "notifications",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notifications_sprint_id"), "notifications", ["sprint_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_task_id"), "notifications", ["task_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_table(
        "sprint_tasks",
        sa.Column("sprint_id", sa.UUID(), nullable=False, comment="ID спринта"),
        sa.Column("task_id", sa.UUID(), nullable=False, comment="ID задачи"),
        sa.Column(
            "order", sa.Integer(), nullable=False, comment="Порядок задачи в спринте"
        ),
        sa.Column(
            "is_added_mid_sprint",
            sa.Boolean(),
            nullable=False,
            comment="Добавлена ли задача в середине спринта",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["sprint_id"],
            ["sprints.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sprint_tasks_id"), "sprint_tasks", ["id"], unique=False)
    op.create_table(
        "time_entries",
        sa.Column("description", sa.Text(), nullable=True, comment="Описание работы"),
        sa.Column(
            "start_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время начала",
        ),
        sa.Column(
            "end_time",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Время окончания",
        ),
        sa.Column(
            "duration_minutes",
            sa.Integer(),
            nullable=True,
            comment="Длительность в минутах",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активна ли запись"
        ),
        sa.Column("user_id", sa.UUID(), nullable=False, comment="ID пользователя"),
        sa.Column("task_id", sa.UUID(), nullable=False, comment="ID задачи"),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_time_entries_id"), "time_entries", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_time_entries_id"), table_name="time_entries")
    op.drop_table("time_entries")
    op.drop_index(op.f("ix_sprint_tasks_id"), table_name="sprint_tasks")
    op.drop_table("sprint_tasks")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_task_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_sprint_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_project_id"), table_name="notifications")
    op.drop_index(
        op.f("ix_notifications_notification_type"), table_name="notifications"
    )
    op.drop_index(op.f("ix_notifications_is_read"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_comments_id"), table_name="comments")
    op.drop_table("comments")
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_sprints_id"), table_name="sprints")
    op.drop_table("sprints")
    op.drop_index(op.f("ix_project_members_id"), table_name="project_members")
    op.drop_table("project_members")
    op.drop_index(op.f("ix_projects_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
