"""Добавление Story Points в модель задач

Revision ID: 5bd0c44c2caa
Revises:
Create Date: 2026-02-04 00:57:48.719149

"""

# revision identifiers, used by Alembic.
revision = "5bd0c44c2caa"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
