"""Add analytics tables

Revision ID: a1dafd8ebd3e
Revises: c71c96ca53d9
Create Date: 2026-02-05 08:43:23.638137

"""

# revision identifiers, used by Alembic.
revision = "a1dafd8ebd3e"
down_revision = "c71c96ca53d9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
