"""Исправление типов UUID в моделях Sprint и SprintTask

Revision ID: e4a2a9af004e
Revises: 4a1a21497fc2
Create Date: 2026-02-03 04:43:59.313742

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e4a2a9af004e"
down_revision = "4a1a21497fc2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comments",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "project_members",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "projects",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "sprint_tasks",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "sprints",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "tasks",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "time_entries",
        "start_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_comment="Время начала",
    )
    op.alter_column(
        "time_entries",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.alter_column(
        "time_entries",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.alter_column(
        "time_entries",
        "start_time",
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_comment="Время начала",
    )
    op.alter_column(
        "tasks",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.alter_column(
        "sprints",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.alter_column(
        "sprint_tasks",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.alter_column(
        "projects",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.alter_column(
        "project_members",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    op.alter_column(
        "comments",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("uuid_generate_v4()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
